### ISSUE TITLE
Text field overflow 

### ISSUE THREAD

**Issue by NabilaAhmedAdity** [forthright48/chat-app#4] opened 2016-06-23 06:40 UTC
Well, there there is an another problem. Number of text lines also overflow and cannot see on screen. Your text field is showing old text lines and hiding new text lines. Where it should do exactly the opposite task.

**Comment by forthright48** [comment] 2016-06-23 08:27
Duplicate of issue #2

**Closed as completed** 2016-06-23 08:28 UTC
